language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Q450xe5ck30hkGak7ZT0jd0xyKmm2EvFgQ/cbfbl8Ja2/Awr0YfqjfbRqqHoO6iCquvxx94fAy1Wk2XSUtoqElGEaAEZFiYBH+izHwnedhR3wTDgkTh/5EutBQ4A04RMTlIhLIvrfKQenz4hCazNokoEYFDkQq5KYyJSC5Wq5jop3DAOilcf0RWP9OVs3zwxITd/7RnT71E00tI6VVMGtpQPKjptNn2glmpxF9FjKCz7yOSA7sFTuFcvgTFewKvtEEw+TLhhGXMYyPntXczX15uftHH2xXFZfyz8cLyU0DWSBsYdjbnLoKuGQuCRxNkxze+dcJOdnnjp/j0buZvF3k5CZ4j7GuGYrQGOWMAODdWWXNCu1kyq9pwNxbg0WTfYz2QW+09sHynsVzfla4hncUqadgINl+NLWVWrx9zhG8qyKyewVjNdZnJ9SC37yFTCT2hT1wuJKdjX+jeoSkX+7VRaVYbJYneB4UbuKAp3r9yg9X7xqViTqYeTSeATHdOA+ElD6k8tDvF2+8FJ8e3N+3HCWeLQqykz91XPEKoh3geUDmei78/bZVoEXEMrZbzdr+/vPRsNgp3GnGOJYdfhZ7IA3wUzZM7bBZ99rrrQwmQL9MkgMxjJxiE545k8Igfc9wgu64Y5uYjHRjJMJaP4fYGwd7pzeJZgkhriyT8xXqM=
  app: eras-api
  on:
    repo: Turing-Eras/api
    branch: main
  skip_cleanup: 'true'
notifications:
  email:
    on_success: never
    on_failure: never
cache:
- bundler
