version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  heroku: circleci/heroku@0.0.10. 


jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          PGHOST: localhost
          PGUSER: sweater-weater-api
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: sweater-weater-api
          POSTGRES_DB: sweater-weater-api_test
          POSTGRES_PASSWORD: "password test"
    working_directory: ~/Turing-Eras/api
    executor: ruby/default
    steps:
      - checkout
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      # Database setup
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rspec
